### ISSUE TITLE
Zły komunikat przy przydzielaniu daily FC

### ISSUE THREAD

**Issue by breakgimme** [fratik/FratikB0T#15]
Przy przydzielaniu daily jesteśmy poinformowani że dostajemy 500 z okazji świąt (których nawet dzisiaj nie ma) a tak naprawde dostajemy 250.
![image](https://user-images.githubusercontent.com/30757793/69863430-0e75fb80-129d-11ea-9a09-f73fc1d8e19d.png)

**Comment by KAMIL0024** [comment]
XD, pozdrawiam osoby, które to sprzedały.

**Comment by fratik** [comment]
przydzielone issue id na boardzie ~dlaczego nikt tego nie napisał~: FB0T-113
