### ISSUE TITLE
Wysyłanie odpowiedzi do wiadomości z filmem nie działa.

### ISSUE THREAD

**Issue by breakgimme** [fratik/FratikB0T#76]
![image](https://user-images.githubusercontent.com/30757793/73385798-11f22700-42ce-11ea-80fa-eed3a5e80a60.png)

**Comment by breakgimme** [comment]
![image](https://user-images.githubusercontent.com/30757793/75632149-913e8780-5bf9-11ea-94c4-6a46898fd526.png)
niby juz dziala ale jednak nie dziala

**Comment by breakgimme** [comment]
a nie czekaj bo to cos innego bylo

**Comment by breakgimme** [comment]
![image](https://user-images.githubusercontent.com/30757793/75632180-ce0a7e80-5bf9-11ea-8cb0-6a9e1dfd589d.png)
po minucie oczekiwania dzieje sie to

**Comment by fratik** [comment]
możliwe że naprawione

**Comment by fratik** [comment]
brak odpowiedzi, uznaje za rozwiązane
