### ISSUE TITLE
autor bota robi spambota i usuwa tego bo niby ma za malo hajsu a teraz kupil switcha

### ISSUE THREAD

**Issue by breakgimme** [fratik/FratikB0T#85]
taki jego wyglad jest

**Comment by KAMIL0024** [comment]
Naprawione w ostatnim buildzie.

**Comment by fratik** [comment]
co XD

**Comment by fratik** [comment]
SW-0107-0462-0052 btw

**Comment by breakgimme** [comment]
> SW-0107-0462-0052 btw

SW-0596-0130-7336 btw

**Comment by breakgimme** [comment]
jednak nie ma hajsu ma 20zł na koncie pozdrawiam

**Comment by fratik** [comment]
Teraz tylko wytrwać do pierwszego ![A8B3CEAD-2994-4B37-8D65-CD46FB53FF71](https://user-images.githubusercontent.com/28189051/77803678-fb720d00-707d-11ea-9cb5-a46b31fd290a.jpeg)
